stages:
  - test

variables:
  PYTHONPATH: "${PYTHONPATH}:${CI_PROJECT_DIR}"  # Add project directory to PYTHONPATH

test:
  stage: test
  image: python:3.11  # Choose the appropriate Python version
  before_script:
    - apt-get update -qy && apt-get install -y python3-pip  # Install pip dependencies
    - pip install -r requirements.txt  # Install project dependencies
  script:
    - python -m unittest discover -s tests -p 'test_*.py'  # Run unit tests

