test:
  stage: test
  image: python:3.11
  before_script:
    - apt-get update -qy && apt-get install -y python3-pip
    - pip install -r requirements.txt
    - pwd  # Print the present working directory
    - ls -la  # List all files and directories in the current working directory
    - ls -la sprites/gameobjects/  # Specifically check if Bomb.png is in the expected directory
  script:
    - python -m unittest discover -s tests -p 'test_*.py'

